plugins {
    id "com.diffplug.spotless" version "8.0.0"
}

defaultTasks 'build'

tasks.named('build') {
    dependsOn gradle.includedBuilds.collect { it.task(':build') }
}

tasks.named('clean') {
    dependsOn gradle.includedBuilds.collect { it.task(':clean') }
}

spotless {
    java {
        target fileTree(rootDir) {
            include "**/*.java"
            exclude "**/build/**", "**/.gradle/**", "**/stage0/snippets/**", "**/stage0/templates/**", "**/stage0/solutions/**", "**/stage1/snippets/**"
        }
        licenseHeaderFile rootProject.file('gradle/LICENSE_HEADER')
    }
}

tasks.named('spotlessCheck') {
    dependsOn gradle.includedBuilds.collect { it.task(':spotlessCheck') }
}

tasks.named('spotlessApply') {
    dependsOn gradle.includedBuilds.collect { it.task(':spotlessApply') }
}
