name: Sync to Target Repos (Copybara)

on:
    push:
        branches:
            - main
        paths:
            - 'examples/stage0/**'
            - 'examples/stage1/**'
            - 'examples/LICENSE'
            - 'copy.bara.sky'
            - '.github/workflows/copybara.yml'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    detect:
        if: github.ref == 'refs/heads/main' && github.repository == 'frcsoftware/frcsoftware.org'
        runs-on: ubuntu-latest

        outputs:
            workflows: ${{ steps.filter.outputs.changes }}

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Determine changed workflows
              uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      stage0_solution:
                        - &lic 'examples/LICENSE'
                        - &sky 'copy.bara.sky'
                        - &wfl '.github/workflows/copybara.yml'
                        - 'examples/stage0/solutions/**'
                      stage0_template: [*lic, *sky, *wfl, 'examples/stage0/templates/**']
                      stage1a_rev_solution: [*lic, *sky, *wfl, 'examples/stage1/stage1a/solutions/rev/**']
                      stage1a_ctre_solution: [*lic, *sky, *wfl, 'examples/stage1/stage1a/solutions/ctre/**']
                      stage1b_rev_solution: [*lic, *sky, *wfl, 'examples/stage1/stage1b/solutions/rev/**']
                      stage1b_ctre_solution: [*lic, *sky, *wfl, 'examples/stage1/stage1b/solutions/ctre/**']
                      stage1a_rev_template: [*lic, *sky, *wfl, 'examples/stage1/templates/rev/**']
                      stage1a_ctre_template: [*lic, *sky, *wfl, 'examples/stage1/templates/ctre/**']
                      stage1b_rev_template: [*lic, *sky, *wfl, 'examples/stage1/templates/rev/**']
                      stage1b_ctre_template: [*lic, *sky, *wfl, 'examples/stage1/templates/ctre/**']

    copybara:
        needs: detect
        if: needs.detect.outputs.workflows != '[]'
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                workflow: ${{ fromJSON(needs.detect.outputs.workflows) }}

        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Setup Java
              uses: actions/setup-java@v6
              with:
                  distribution: 'temurin'
                  java-version: '25'

            - name: Configure Git Auth
              run: |
                  # Set global git user for commits
                  git config --global user.name "Automated Sync"
                  git config --global user.email "noreply@frcsoftware.org"

                  # Configure git to use your PAT for all HTTPS connections to GitHub
                  git config --global url."https://x-access-token:${{ secrets.COPYBARA_PAT }}@github.com/".insteadOf "https://github.com/"
            - name: Download Copybara
              run: wget https://github.com/google/copybara/releases/download/v20260824/copybara_deploy.jar

            - name: Run Copybara
              run: java -jar copybara_deploy.jar copy.bara.sky ${{ matrix.workflow }} --force --ignore-noop || test $? -eq 4
